name: Run tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.203

    - name: Restore dependencies
      run: dotnet restore lab5

    - name: Build project
      run: dotnet build lab5

    - name: Run tests
      run: dotnet test lab5
